# Veamos con un ejemplo el uso de concat - merge - join

Contamos con dos estaciones meteorológicas, cada una instalada en una ubicación geográfica diferente, que sensan datos de temperatura, presión y humedad cada una hora.
<BR>
Simulemos algunas mediciones y armemos dos dataframes, uno para cada estación y con datos de un mismo día

In [ ]:
import pandas as pd
import numpy as np

# Creamos una serie tipo datetime con 24 valores, mismo día y 24 horas.
horas = pd.date_range("2025-10-11 00:00", periods=24, freq="H")
horas

In [ ]:
# Simulamos el dataframe de la Estacion 1
estacion1 = pd.DataFrame({
    "hora": horas,
    "estacion": "E1",
    "temperatura": np.random.normal(20, 3, 24),  # genera 24 valores (dist normal) con media 20 y desviación 3
    "presion": np.random.normal(1013, 5, 24),  # genera 24 valores (dist normal) con media 1013 y desviación 5
    "humedad": np.random.uniform(40, 80, 24)  # genera 24 valores (dist uniform) con media 40 y desviación 8
})

In [ ]:
estacion1.sample()

In [ ]:
import matplotlib.pyplot as plt
estacion1["temperatura"].hist(bins="auto")
plt.show()

In [ ]:
# Graficamos las temperaturas de 1 día
estacion1.plot(x="hora", y="temperatura", kind="line")
plt.show()

In [ ]:
# Simulamos el dataframe de la Estacion 1
estacion2 = pd.DataFrame({
    "hora": horas,
    "estacion": "E2",
    "temperatura": np.random.normal(18, 2, 24),
    "presion": np.random.normal(1010, 4, 24),
    "humedad": np.random.uniform(35, 75, 24)
})

In [ ]:
estacion2.sample()

## concat - Unificamos dos datasets usando concat

 La forma más natural de unificarlos en pandas es usando:
<BR>
`pd.concat()`
<BR>
Sirve para apilar DataFrames (uno debajo del otro o lado a lado).
Es ideal cuando los DataFrames tienen las mismas columnas (por ejemplo, mismo formato de mediciones de distintas estaciones).
<BR>
Por default, apila los datos verticalmente (uno debajo de otro), por lo que `axis = 0`
<BR>
Para ubicar los dataframes, uno seguido del otro, usamos el argumento `axis = 1`
<BR>
Cada dataframe tiene su index, por lo que es buena práctica al usar concat, regenerar el index en el dataframe resultante, para ello usamos `ignore_index=True`

In [ ]:
# Unificamos los datos de ambas estaciones

## merge - une los dataframes por una columna en común
Lo usamos para comparar las mediciones de las estaciones

In [ ]:
# Merge por la columna 'hora' (igual que un JOIN ON hora)

## join - une los dataframes por el index

In [ ]:
# Establecemos 'hora' como índice

In [ ]:
# Unimos por índice (hora)

In [ ]:
# Unimos solo la columna 'temperatura' de la segunda estación

In [ ]:
# Unimos solo las columnas de temperatura de ambas estaciones

In [ ]:
# Vere un gráfico comparativo

Si trabajás con datos horarios o diarios, join() es muy cómodo porque muchas veces ya tenés el tiempo como índice (DatetimeIndex). Te permite hacer operaciones de series temporales como:

# Importamos Dataset Booking - Hotels - Users
https://www.kaggle.com/code/sonawanelalitsunil/international-hotel-booking-analytics-ml-34-75/notebook

In [ ]:
# Importar la librería Pandas
import pandas as pd

In [ ]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Verificar que los archivos csv se encuentren en la carpeta datasets
import os
os.listdir("/content/drive/MyDrive/datasets")

In [ ]:
# Cambiamos el directorio para importar con facilidad
os.chdir("/content/drive/MyDrive/datasets")
os.listdir(".")

In [ ]:
# Importamos Reviews
reviews = pd.read_csv('reviews.csv')

In [ ]:
# Importamos Hotels
hotels = pd.read_csv('hotels.csv')

In [ ]:
# Importamos Users
users = pd.read_csv('users.csv')

## Actividad 1 (Dificultad *)
Reproducir la siguiente consulta SQL con Pandas


```
select h.hotel_name, h.country, r.score_overall
from  hotels h join reviews r
on h.hotel_id == r.hotel_id
```

In [ ]:
# Merge (equivalente al SQL JOIN)

In [ ]:
# Seleccionamos solo las columnas que nos solicitan

## Actividad 2 (Dificultad *)
Reproducir la siguiente consulta SQL con Pandas


```
select h.hotel_name, h.country, avg(r.score_overall) as avg_score
from  hotels h join reviews r
on h.hotel_id == r.hotel_id
GROUP by h.hotel_name, h.country
```

In [ ]:
# Merge (equivalente al SQL JOIN)

In [ ]:
# Agrupación / Agregación

## Actividad 3 (Dificultad ***)
Reproducir la siguiente consulta SQL con Pandas


```
select h.hotel_name, h.country, avg(r.score_overall) as avg_score
from  hotels h join reviews r
on h.hotel_id == r.hotel_id
WHERE h.country like '%argentina%'
GROUP by h.hotel_name, h.country
```

In [ ]:
# Merge (equivalente al SQL JOIN)

In [ ]:
# Filtro (equivalente al WHERE con LIKE)

In [ ]:
# Agrupación y promedio (equivalente al GROUP BY y AVG)

## Bonus Track
Usar OpenStreetMap para encontrar la dirección del Hotel

In [ ]:
# https://www.openstreetmap.org/search?lat=-34.6037&lon=-58.3816&zoom=10#map=12/-37.2888/-59.1229